apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mws-applicationset
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  generators:
   - matrix:
      generators:
       - git:
          repoURL: https://github.com/Raisal-A/appsetValues.git
          revision: master
          files:
          - path: '**/*values.yaml'
       - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  cluster_name: cluster
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: production
      sources:
       - repoURL: 'https://github.com/Raisal-A/appsetCharts.git'
         path: '{{ .path.path | splitList "/" | first }}'
         targetRevision: master
         helm:
           valueFiles:
           - $values/{{.path.path}}/{{.path.filename}}
       - repoURL: 'https://github.com/Raisal-A/appsetValues.git'
         targetRevision: master
         ref: values
       - repoURL: 'https://github.com/Raisal-A/appsetEnvs.git'
         path: '{{ .path.path | splitList "/" | first }}'
         targetRevision: master
         helm:
         ref: envs
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
