apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mw-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Raisal-A/appsetValues.git
              revision: master
              files:
                - path: 'nahdi-mw/*-values.yaml'  # For the values.yaml files
          - git:
              repoURL: https://github.com/Raisal-A/appsetEnvs.git  # New repo for environment variables
              revision: master
              files:
                - path: 'nahdi-mw/*-env.yaml'  # For the env.yaml files
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      destination:
        namespace: '{{ .path.filename | replace "-values.yaml" "" }}'
        server: 'https://kubernetes.default.svc'
      project: production
      source:
        helm:
          valueFiles:
            - '{{ .path.path }}'  # This will include the values.yaml file
            - '{{ .path.path | replace "values" "env" }}'  # Manually replace "values" with "env" for env.yaml files
        path: 'nahdi-mw'
        repoURL: https://github.com/Raisal-A/appsetCharts.git
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
